-- Initial DB schema

-- Таблица со всеми пользователями
CREATE TABLE IM_USER (
  IM_USER_ID BIGINT(20) AUTO_INCREMENT NOT NULL,
  ACTIVE BIT(1) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  CONSTRAINT IM_USER_PK PRIMARY KEY (IM_USER_ID),
  CONSTRAINT USERNAME_UN UNIQUE (USERNAME)
);

-- Какие роли существуют
CREATE TABLE IM_ROLE (
  IM_ROLE_ID BIGINT(20) AUTO_INCREMENT NOT NULL,
  NAME varchar(255) NOT NULL,
  ADMIN BIT(1) NOT NULL,
  CONSTRAINT IM_ROLE_PK PRIMARY KEY (IM_ROLE_ID),
  CONSTRAINT NAME_UN UNIQUE (NAME)
);

-- Какая роль у какого пользователя
CREATE TABLE IM_USER_ROLE (
  IM_USER_ID BIGINT(20) NOT NULL,
  IM_ROLE_ID BIGINT(20) NOT NULL,
  CONSTRAINT IM_USER_ROLE_PK PRIMARY KEY (IM_USER_ID, IM_ROLE_ID),
  CONSTRAINT IM_USER_ID_FK FOREIGN KEY (IM_USER_ID) REFERENCES IM_USER(IM_USER_ID),
  CONSTRAINT IM_ROLE_ID_FK FOREIGN KEY (IM_ROLE_ID) REFERENCES IM_ROLE(IM_ROLE_ID)
);

-- таблица с сообщениями (id сообщения, сам текст сообщения, от кого идет сообщения, кому идут сообщения)
CREATE TABLE IM_MESSAGE (
  IM_MESSAGE_ID BIGINT(20) AUTO_INCREMENT NOT NULL,
  TEXT VARCHAR(255) NOT NULL,
  FROM_IM_USER_ID BIGINT(20) NOT NULL,
  TO_IM_USER_ID BIGINT(20) NOT NULL,
  CONSTRAINT IM_MESSAGE_PK PRIMARY KEY (IM_MESSAGE_ID),
  CONSTRAINT FROM_IM_USER_ID_FK FOREIGN KEY (FROM_IM_USER_ID) REFERENCES IM_USER(IM_USER_ID),
  CONSTRAINT TO_IM_USER_ID_FK FOREIGN KEY (TO_IM_USER_ID) REFERENCES IM_USER(IM_USER_ID)
);
