version: '3.1'

services:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_DATABASE: 'imdemo'
      MYSQL_USER: 'imdemo'
      MYSQL_PASSWORD: 'imdemo'
      MYSQL_ROOT_PASSWORD: 'imdemo'
      LC_ALL: ru_RU.UTF-8
      LANG: ru_RU.UTF-8
    ports:
      - 3306:3306
